type: docker
kind: pipeline
name: test

trigger:
  event: [push]

services:
  - name: postgres
    image: postgres:12
    ports: [5432]
    environment:
      POSTGRES_USER: nest-nuxt-boilerplate
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nest-nuxt-boilerplate-test

steps:
  - name: test
    image: node:14.16.0-slim
    environment:
      NODE_ENV: test
      TYPEORM_URL: postgres://nest-nuxt-boilerplate:secret@postgres:5432/nest-nuxt-boilerplate-test
      TYPEORM_MIGRATIONS: "db/migrate/*.ts"
      JWT_SECRET: secret
      CSRF_SECRET: secret
    commands:
      - apt update && apt install python g++ build-essential git -y && apt-get clean
      - yarn install --pure-lockfile
      - yarn lint
      - yarn db:migrate
      - yarn generate:types
      - yarn test
    depends_on: [clone]
---
type: docker
kind: pipeline
name: build

trigger:
  event: [push]
  branch: [master]

steps:
  - name: builder
    image: plugins/docker
    settings:
      target: builder
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/nest-nuxt-boilerplate
      tags: builder
      cache_from:
        - quay.io/zebbra/nest-nuxt-boilerplate:builder
      custom_labels: [quay.expires-after=30d]
      mtu: 1316

  - name: release
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/nest-nuxt-boilerplate
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
      cache_from:
        - quay.io/zebbra/nest-nuxt-boilerplate:builder
        - quay.io/zebbra/nest-nuxt-boilerplate:latest
      mtu: 1316
---
type: docker
kind: pipeline
name: deploy

trigger:
  event: [push]
  branch: [master]

steps:
  - name: helm
    image: pelotech/drone-helm3
    environment:
      KUBE_API_SERVER: https://kubernetes.default
      KUBE_TOKEN: { from_secret: kubernetes_token }
    settings:
      mode: upgrade
      chart: ./deploy/nest-nuxt-boilerplate
      release: nest-nuxt-boilerplate
      namespace: demo
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7}
      values_files: [deploy/values.yaml]
      skip_tls_verify: true

depends_on:
  - test
  - build
